import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import LeftSidebar from 'components/layouts/LeftSidebar';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <main className="flex">
          <LeftSidebar />
          <div className="flex-none w-full h-full m-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
